logging:
  level:
    org.springframework.security: INFO
# strix:
 # command:
   # default:
    #  execution:
       # isolation:
      #    thread:
       #     timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#security:
#  oauth2:
  #  resource:
   #   user-info-uri: http://auth-service:5000/uaa/users/current

#spring:
  #rabbitmq:
   # host: rabbitmq