security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${PROPERTY_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/property-service

server:
  servlet:
    context-path: /property
  port: 7000